config/routes.rb
Rails.application.routes.draw do
  resources :inventories

  devise_for :users
  root'pages#home'

  get 'pages/about'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, expect: [:index,:show]

  respond_to :html

  def index
    @inventories = Inventory.all
    respond_with(@inventories)
  end

  def show
    respond_with(@inventory)
  end

  def new
    @inventory = current_user.inventories.build
    respond_with(@inventory)
  end

  def edit
  end

  
  def create
    @inventory = current_user.inventories.build(inventory_params)

      if @inventory.save
       redirect_to @inventory, notice: 'Inventory was successfully created.' 
      else
        render action: 'new' 
      end
  end


  def update
    @inventory.update(inventory_params)
    respond_with(@inventory)
  end

  def destroy
    @inventory.destroy
    respond_with(@inventory)
  end

  private
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    def inventory_params
      params.require(:inventory).permit(:Name, :Description, :Price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="form-group">
    <%= f.label :Description %><br>
    <%= f.text_field :Description %>
  </div>
  <div class="form-group">
    <%= f.label :Price %><br>
    <%= f.text_field :Price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<h1>Listing inventories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div id="inventories" class="transitions-enbaled">
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.Name %></td>
        <td><%= inventory.Description %></td>
        <td><%= inventory.Price %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inventory.Name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inventory.Description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.Price %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Denilson", root_path, class:"navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      </li>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "About", "#"%></li>

       <% if user_signed_in? %>
      <li><%= link_to new_inventory_path  do%>
      <span class="glyphicon glyphicon-plus"></span> New Item
    <%end%>
      <li><%= link_to "Account Settings", edit_user_registration_path%></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
      <% else %>
      <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /. container -->
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Denilson</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do|name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
  	<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Denilson is a mobile payments solution for businesses that enables everybody on the team to accept mobile payments anytime, anywhere.</p>

<p>Interested in joining our team? Please tell us about yourself at career@denilson.co</p>
<br>
<br>
<p> Want to get in touch? Drop us a line at info@denilson.co </p>

app/views/pages/home.html.erb
<div class="jumbotron center">	
<h1>Denilson</h1>
<p>Accept mobile payments anytime, anywhere.</p>
<br>
<br>
<br>

<p>
	Click here to <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-lg"%> <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default btn-lg"%>
</p>
</div>